server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
